org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.nonFinalResIds=true
android.defaults.buildfeatures.resvalues=false
android.enableAppCompileTimeRClass=true
android.r8.optimizedResourceShrinking=true
android.builtInKotlin=true
android.newDsl=true
android.dependency.excludeLibraryComponentsFromConstraints=true